config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/new'

  get 'users/create'

  # CRUD
  resources :articles

  # VOTING
  patch '/articles/:id/upvote', to: "articles#upvote", as: :upvote

  patch '/articles/:id/downvote', to: "articles#downvote", as: :downvote


  # LOGIN
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'

  # USERS
    get '/signup', to: 'users#new'
    post '/users', to: 'users#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  def upvote
    self.votes += 1
    self.save
  end

  def downvote
    self.votes -= 1
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Update the application controller with new methods
  # to look up the user, if they're logged in, and save their user object
  # to a variable called @current_user.
  # The helper_method line below current_user allows us to use
  # @current_user in our view files.
  # Authorize is for sending someone to the login page if they aren't logged in
  # - this is how we keep certain pages our site secure...
  # user's have to login before seeing them.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  # Add a before_filter to any controller that you want to secure.
  # This will force user's to login before they can see the actions in this controller.
  # I've created a gif controller below which I'm going to secure.
  # The routes for this controller were added to the routes.rb in the beginning of this tutorial.

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_filter :authorize

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @new_article = Article.new
  end

  def create
    new_article = Article.new(articles_params)
    new_article.save
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(articles_params)
    redirect_to articles_path
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  ## VOTERS
  def upvote
    @article.upvote
    redirect_to articles_path
  end

  def downvote
    @article.downvote
    redirect_to articles_path
  end

  ##########################
  private

  def find_article
    @article = Article.find(params[:id])
  end

  def articles_params
    params.require(:article).permit(:name, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to articles_path
    else
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h1>Edit the Article</h1>

<%= form_for @article do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  <%= f.label "Content" %>
  <%= f.text_area :content, :cols => "10", :rows => "10"%>
  <%= f.submit %>
<% end %>

<%= link_to "Home", articles_path %>

app/views/articles/index.html.erb
<h1>All Articles:</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title.capitalize, article_path(article) %>
      <%= ". Votes - #{article.votes}"%>
      <%= link_to "Edit", edit_article_path(article) %>
      <%= link_to upvote_path(article), method: :patch do%>
        <i class="fa fa-chevron-up"></i>
      <% end %>
      <%= link_to downvote_path(article), method: :patch do %>
        <i class="fa fa-chevron-down"></i>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= form_for @new_article do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  <%= f.label "Content" %>
  <%= f.text_area :content :cols => "10", :rows => "10"%>
  <%= f.submit %>
<% end %>

<%= link_to "Home", articles_path %>

app/views/articles/show.html.erb
<h1>Article</h1>

<div class="container">
  <h2><%= @article.title.capitalize %></h2>
  <p><em><%= @article.content %></em></p>
  <p>Votes: <%= @article.votes %></p>
   <%= link_to "Edit", edit_article_path(@article) %>
</div>

<%= link_to "Home", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if current_user %>
    Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
  <% else %>
    <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>
  <%= f.label "Username" %>
  <%= f.text_field :name %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
   <%= f.label "Confirm Password" %>
  <%= f.password_field :password %>
  <%= f.submit "Submit" %>
<% end %>